name: E2E Tests - Puppeteer (TypeScript)

on:
  workflow_dispatch:
  push:
    branches: [main, master, develop]
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi
      
      - name: Build TypeScript
        run: |
          if [ -f "yarn.lock" ]; then
            yarn build --if-present || true
          else
            npm run build --if-present || true
          fi
        continue-on-error: true
      
      - name: Run E2E Tests
        run: npm test cirq-web/cirq_ts/e2e/bloch_sphere/bloch_sphere_e2e_test.ts cirq-web/cirq_ts/e2e/circuit/circuit_e2e_test.ts
